
#pragma once

#if defined(ARDUINO_ESP32C3_DEV)

#include "../PinDefinition.h"

const char* BOARD_NAME = "ESP32-C3-DevKitM-1";
const char* BOARD_ID = "esp32-c3-devkitm-1";

PinDefinition board_pins[] = {
    // GPIO, Supported Modes (IN, IN_UP, IN_DN, ADC, TOUCH, OUT, OUT_OD, PWM, DAC)
    {0, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_ADC | PIN_CAP_OUT | PIN_CAP_PWM},
    {1, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_ADC | PIN_CAP_OUT | PIN_CAP_PWM},
    {2, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_ADC | PIN_CAP_TOUCH | PIN_CAP_OUT | PIN_CAP_PWM},
    {3, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_ADC | PIN_CAP_TOUCH | PIN_CAP_OUT | PIN_CAP_PWM},
    {4, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_ADC | PIN_CAP_TOUCH | PIN_CAP_OUT | PIN_CAP_PWM},
    {5, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_ADC | PIN_CAP_TOUCH | PIN_CAP_OUT | PIN_CAP_PWM},
    {6, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_TOUCH | PIN_CAP_OUT | PIN_CAP_PWM},
    {7, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_TOUCH | PIN_CAP_OUT | PIN_CAP_PWM},
    {8, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_OUT | PIN_CAP_PWM},
    {9, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_OUT | PIN_CAP_PWM},
    {10, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_OUT | PIN_CAP_PWM},
    {18, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_OUT},
    {19, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_OUT},
    {20, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_OUT},
    {21, PIN_CAP_IN | PIN_CAP_IN_UP | PIN_CAP_IN_DN | PIN_CAP_OUT},
};

const int board_pin_count = sizeof(board_pins) / sizeof(board_pins[0]);

#endif
