#pragma once
#include <Arduino.h>

// ─── Board Identity ───────────────────────────────────────────────
#if defined(ARDUINO_LOLIN_S3_MINI)
  #define BOARD_NAME "Lolin S3 Mini"
  #define BOARD_ID   "lolin_s3_mini"

#elif defined(ARDUINO_ESP32S3_DEV)
  #define BOARD_NAME "ESP32-S3 Dev Board"
  #define BOARD_ID   "esp32s3"

#elif defined(ARDUINO_ESP32_DEV) || defined(ESP32)
  #define BOARD_NAME "ESP32 Dev Board"
  #define BOARD_ID   "esp32"

#elif defined(ARDUINO_AVR_UNO)
  #define BOARD_NAME "Arduino Uno"
  #define BOARD_ID   "uno"

#elif defined(ARDUINO_AVR_MEGA2560)
  #define BOARD_NAME "Arduino Mega 2560"
  #define BOARD_ID   "mega2560"

#elif defined(ARDUINO_RASPBERRY_PI_PICO)
  #define BOARD_NAME "Raspberry Pi Pico (RP2040)"
  #define BOARD_ID   "rp2040"

#else
  #define BOARD_NAME "Unknown Board"
  #define BOARD_ID   "unknown"
#endif

// ─── Pin Capability Flags ─────────────────────────────────────────
#define CAP_IN       (1 << 0)  // Digital INPUT
#define CAP_IN_UP    (1 << 1)  // INPUT_PULLUP
#define CAP_IN_DN    (1 << 2)  // INPUT_PULLDOWN
#define CAP_ADC      (1 << 3)  // Analog Input
#define CAP_TOUCH    (1 << 4)  // Capacitive Touch
#define CAP_OUT      (1 << 5)  // Digital OUTPUT
#define CAP_OUT_OD   (1 << 6)  // OUTPUT_OPEN_DRAIN
#define CAP_PWM      (1 << 7)  // PWM
#define CAP_DAC      (1 << 8)  // True Analog / DAC

struct PinDef {
  const char* name;
  uint16_t    caps;   // bitmask of CAP_* flags
};

// ─── Board-specific pin tables ────────────────────────────────────

#if defined(ARDUINO_LOLIN_S3_MINI) || defined(ARDUINO_ESP32S3_DEV)
// ESP32-S3: 45 usable GPIOs (GPIO0-GPIO21, GPIO26-GPIO48)
// ADC1: GPIO1-GPIO10  ADC2: GPIO11-GPIO20 (ADC2 unusable w/ WiFi)
// DAC: none on S3     TOUCH: GPIO1-GPIO14
// OD: all output-capable pins support open-drain
static const PinDef BOARD_PINS[] = {
  {"GPIO0",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO1",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO2",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO3",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO4",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO5",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO6",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO7",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO8",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO9",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO10", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO11", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO12", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO13", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO14", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO15", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO16", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO17", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO18", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO19", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO20", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO21", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO26", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO33", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO34", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO35", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO36", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO37", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO38", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO39", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO40", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO41", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO42", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO43", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},  // TX0
  {"GPIO44", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},  // RX0
  {"GPIO45", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO46", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO47", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO48", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
};

#elif defined(ESP32)
// Classic ESP32: ADC1 GPIO32-39, ADC2 GPIO0,2,4,12-15,25-27
// DAC: GPIO25, GPIO26   TOUCH: GPIO0,2,4,12-15,27,32-33
static const PinDef BOARD_PINS[] = {
  {"GPIO0",  CAP_IN|CAP_IN_UP|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO2",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO4",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO5",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO12", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO13", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO14", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO15", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO16", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO17", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO18", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO19", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO21", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO22", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO23", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO25", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_OUT|CAP_OUT_OD|CAP_PWM|CAP_DAC},
  {"GPIO26", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_OUT|CAP_OUT_OD|CAP_PWM|CAP_DAC},
  {"GPIO27", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO32", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO33", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_TOUCH|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GPIO34", CAP_IN|CAP_ADC},
  {"GPIO35", CAP_IN|CAP_ADC},
  {"GPIO36", CAP_IN|CAP_ADC},
  {"GPIO39", CAP_IN|CAP_ADC},
};

#elif defined(ARDUINO_AVR_UNO)
static const PinDef BOARD_PINS[] = {
  {"D0",  CAP_IN|CAP_IN_UP|CAP_OUT},
  {"D1",  CAP_IN|CAP_IN_UP|CAP_OUT},
  {"D2",  CAP_IN|CAP_IN_UP|CAP_OUT},
  {"D3",  CAP_IN|CAP_IN_UP|CAP_OUT|CAP_PWM},
  {"D4",  CAP_IN|CAP_IN_UP|CAP_OUT},
  {"D5",  CAP_IN|CAP_IN_UP|CAP_OUT|CAP_PWM},
  {"D6",  CAP_IN|CAP_IN_UP|CAP_OUT|CAP_PWM},
  {"D7",  CAP_IN|CAP_IN_UP|CAP_OUT},
  {"D8",  CAP_IN|CAP_IN_UP|CAP_OUT},
  {"D9",  CAP_IN|CAP_IN_UP|CAP_OUT|CAP_PWM},
  {"D10", CAP_IN|CAP_IN_UP|CAP_OUT|CAP_PWM},
  {"D11", CAP_IN|CAP_IN_UP|CAP_OUT|CAP_PWM},
  {"D12", CAP_IN|CAP_IN_UP|CAP_OUT},
  {"D13", CAP_IN|CAP_IN_UP|CAP_OUT},
  {"A0",  CAP_IN|CAP_IN_UP|CAP_ADC|CAP_OUT},
  {"A1",  CAP_IN|CAP_IN_UP|CAP_ADC|CAP_OUT},
  {"A2",  CAP_IN|CAP_IN_UP|CAP_ADC|CAP_OUT},
  {"A3",  CAP_IN|CAP_IN_UP|CAP_ADC|CAP_OUT},
  {"A4",  CAP_IN|CAP_IN_UP|CAP_ADC|CAP_OUT},
  {"A5",  CAP_IN|CAP_IN_UP|CAP_ADC|CAP_OUT},
};

#elif defined(ARDUINO_RASPBERRY_PI_PICO)
static const PinDef BOARD_PINS[] = {
  {"GP0",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP1",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP2",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP3",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP4",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP5",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP6",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP7",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP8",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP9",  CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP10", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP11", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP12", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP13", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP14", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP15", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP16", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP17", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP18", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP19", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP20", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP21", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP22", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP26", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP27", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_OUT|CAP_OUT_OD|CAP_PWM},
  {"GP28", CAP_IN|CAP_IN_UP|CAP_IN_DN|CAP_ADC|CAP_OUT|CAP_OUT_OD|CAP_PWM},
};

#else
// Fallback: single generic pin
static const PinDef BOARD_PINS[] = {
  {"D0", CAP_IN|CAP_IN_UP|CAP_OUT},
};
#endif

static const uint8_t PIN_COUNT = sizeof(BOARD_PINS) / sizeof(BOARD_PINS[0]);

// Map pin name string → Arduino pin number
inline int pinNameToNumber(const char* name) {
#if defined(ARDUINO_LOLIN_S3_MINI) || defined(ARDUINO_ESP32S3_DEV) || defined(ESP32)
  // GPIOxx → integer
  if (strncmp(name, "GPIO", 4) == 0) return atoi(name + 4);
#endif
#if defined(ARDUINO_AVR_UNO) || defined(ARDUINO_AVR_MEGA2560)
  if (name[0] == 'D') return atoi(name + 1);
  if (name[0] == 'A') return A0 + atoi(name + 1);
#endif
#if defined(ARDUINO_RASPBERRY_PI_PICO)
  if (strncmp(name, "GP", 2) == 0) return atoi(name + 2);
#endif
  return atoi(name); // fallback: treat as raw number
}
